aws:
  dynamodb:
    tableName: "User"
    secretKey: "12345"
    accessKey: "local"
    endpoint: "http://localhost:8000"
    region: "us-west-2"

security:
  token:
    enabled: true
    bypass: "test"
    keyFilePath: "secrets/local-identity-service-private.key"
    audience: []
    jwtTtlMin: 1
    opaqueTokenTtlHrs: 24

rest:
  customerService:
    baseUrl: "http://localhost:7979/v1/customerservice"
    contentType: "application/json"
    uri:
      addCustomer: "/addcustomer"

server:
  error:
    include-stacktrace: never