server:
  application:
    name: ads-service

security:
  token:
    enabled: true
    bypass: "test"
    keyFilePath: "secrets/local-ads-service-private.key"
    audience: []
    jwtTtlMin: 1
    opaqueTokenTtlHrs: 24